<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class ICD10Seeder extends Seeder
{
    public function run()
    {
        $data = [
            ['uuid' => service('uuid')->uuid4()->toString(), 'code' => 'A00', 'description' => 'Cholera', 'category' => 'Certain infectious and parasitic diseases', 'is_active' => true, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['uuid' => service('uuid')->uuid4()->toString(), 'code' => 'A09', 'description' => 'Infectious gastroenteritis and colitis, unspecified', 'category' => 'Certain infectious and parasitic diseases', 'is_active' => true, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['uuid' => service('uuid')->uuid4()->toString(), 'code' => 'B34.9', 'description' => 'Viral infection, unspecified', 'category' => 'Certain infectious and parasitic diseases', 'is_active' => true, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['uuid' => service('uuid')->uuid4()->toString(), 'code' => 'D50.9', 'description' => 'Iron deficiency anaemia, unspecified', 'category' => 'Diseases of the blood', 'is_active' => true, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['uuid' => service('uuid')->uuid4()->toString(), 'code' => 'D64.9', 'description' => 'Anaemia, unspecified', 'category' => 'Diseases of the blood', 'is_active' => true, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['uuid' => service('uuid')->uuid4()->toString(), 'code' => 'E11.9', 'description' => 'Type 2 diabetes mellitus without complications', 'category' => 'Endocrine, nutritional and metabolic diseases', 'is_active' => true, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['uuid' => service('uuid')->uuid4()->toString(), 'code' => 'E11.65', 'description' => 'Type 2 diabetes mellitus with hyperglycemia', 'category' => 'Endocrine, nutritional and metabolic diseases', 'is_active' => true, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['uuid' => service('uuid')->uuid4()->toString(), 'code' => 'E78.5', 'description' => 'Hyperlipidaemia, unspecified', 'category' => 'Endocrine, nutritional and metabolic diseases', 'is_active' => true, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['uuid' => service('uuid')->uuid4()->toString(), 'code' => 'E03.9', 'description' => 'Hypothyroidism, unspecified', 'category' => 'Endocrine, nutritional and metabolic diseases', 'is_active' => true, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['uuid' => service('uuid')->uuid4()->toString(), 'code' => 'F32.1', 'description' => 'Major depressive disorder, single episode, moderate', 'category' => 'Mental, behavioral and neurodevelopmental disorders', 'is_active' => true, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['uuid' => service('uuid')->uuid4()->toString(), 'code' => 'F41.1', 'description' => 'Generalized anxiety disorder', 'category' => 'Mental, behavioral and neurodevelopmental disorders', 'is_active' => true, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['uuid' => service('uuid')->uuid4()->toString(), 'code' => 'G43.909', 'description' => 'Migraine, unspecified, not intractable, without status migrainosus', 'category' => 'Diseases of the nervous system', 'is_active' => true, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['uuid' => service('uuid')->uuid4()->toString(), 'code' => 'G47.00', 'description' => 'Insomnia, unspecified', 'category' => 'Diseases of the nervous system', 'is_active' => true, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['uuid' => service('uuid')->uuid4()->toString(), 'code' => 'H10.9', 'description' => 'Conjunctivitis, unspecified', 'category' => 'Diseases of the eye', 'is_active' => true, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['uuid' => service('uuid')->uuid4()->toString(), 'code' => 'H65.199', 'description' => 'Other chronic nonsuppurative otitis media, unspecified ear', 'category' => 'Diseases of the ear', 'is_active' => true, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['uuid' => service('uuid')->uuid4()->toString(), 'code' => 'I10', 'description' => 'Essential (primary) hypertension', 'category' => 'Diseases of the circulatory system', 'is_active' => true, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['uuid' => service('uuid')->uuid4()->toString(), 'code' => 'I25.10', 'description' => 'Atherosclerotic heart disease of native coronary artery without angina pectoris', 'category' => 'Diseases of the circulatory system', 'is_active' => true, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['uuid' => service('uuid')->uuid4()->toString(), 'code' => 'I50.9', 'description' => 'Heart failure, unspecified', 'category' => 'Diseases of the circulatory system', 'is_active' => true, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['uuid' => service('uuid')->uuid4()->toString(), 'code' => 'I63.9', 'description' => 'Cerebral infarction, unspecified', 'category' => 'Diseases of the circulatory system', 'is_active' => true, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['uuid' => service('uuid')->uuid4()->toString(), 'code' => 'J06.9', 'description' => 'Acute upper respiratory infection, unspecified', 'category' => 'Diseases of the respiratory system', 'is_active' => true, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['uuid' => service('uuid')->uuid4()->toString(), 'code' => 'J18.9', 'description' => 'Pneumonia, unspecified organism', 'category' => 'Diseases of the respiratory system', 'is_active' => true, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['uuid' => service('uuid')->uuid4()->toString(), 'code' => 'J20.9', 'description' => 'Acute bronchitis, unspecified', 'category' => 'Diseases of the respiratory system', 'is_active' => true, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['uuid' => service('uuid')->uuid4()->toString(), 'code' => 'J45.20', 'description' => 'Mild intermittent asthma, uncomplicated', 'category' => 'Diseases of the respiratory system', 'is_active' => true, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['uuid' => service('uuid')->uuid4()->toString(), 'code' => 'J45.909', 'description' => 'Unspecified asthma, uncomplicated', 'category' => 'Diseases of the respiratory system', 'is_active' => true, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['uuid' => service('uuid')->uuid4()->toString(), 'code' => 'K21.0', 'description' => 'Gastro-esophageal reflux disease with esophagitis', 'category' => 'Diseases of the digestive system', 'is_active' => true, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['uuid' => service('uuid')->uuid4()->toString(), 'code' => 'K29.70', 'description' => 'Gastritis, unspecified, without bleeding', 'category' => 'Diseases of the digestive system', 'is_active' => true, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['uuid' => service('uuid')->uuid4()->toString(), 'code' => 'K58.9', 'description' => 'Irritable bowel syndrome without diarrhea', 'category' => 'Diseases of the digestive system', 'is_active' => true, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['uuid' => service('uuid')->uuid4()->toString(), 'code' => 'K80.20', 'description' => 'Calculus of gallbladder without cholecystitis without obstruction', 'category' => 'Diseases of the digestive system', 'is_active' => true, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['uuid' => service('uuid')->uuid4()->toString(), 'code' => 'L30.9', 'description' => 'Dermatitis, unspecified', 'category' => 'Diseases of the skin', 'is_active' => true, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['uuid' => service('uuid')->uuid4()->toString(), 'code' => 'L40.9', 'description' => 'Psoriasis, unspecified', 'category' => 'Diseases of the skin', 'is_active' => true, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['uuid' => service('uuid')->uuid4()->toString(), 'code' => 'M54.5', 'description' => 'Low back pain', 'category' => 'Diseases of the musculoskeletal system', 'is_active' => true, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['uuid' => service('uuid')->uuid4()->toString(), 'code' => 'M54.9', 'description' => 'Dorsalgia, unspecified', 'category' => 'Diseases of the musculoskeletal system', 'is_active' => true, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['uuid' => service('uuid')->uuid4()->toString(), 'code' => 'M79.3', 'description' => 'Panniculitis, unspecified', 'category' => 'Diseases of the musculoskeletal system', 'is_active' => true, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['uuid' => service('uuid')->uuid4()->toString(), 'code' => 'N10', 'description' => 'Acute pyelonephritis', 'category' => 'Diseases of the genitourinary system', 'is_active' => true, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['uuid' => service('uuid')->uuid4()->toString(), 'code' => 'N39.0', 'description' => 'Urinary tract infection, site not specified', 'category' => 'Diseases of the genitourinary system', 'is_active' => true, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['uuid' => service('uuid')->uuid4()->toString(), 'code' => 'O80', 'description' => 'Encounter for full-term uncomplicated delivery', 'category' => 'Pregnancy, childbirth and the puerperium', 'is_active' => true, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['uuid' => service('uuid')->uuid4()->toString(), 'code' => 'R05.9', 'description' => 'Cough, unspecified', 'category' => 'Symptoms, signs and abnormal clinical and laboratory findings', 'is_active' => true, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['uuid' => service('uuid')->uuid4()->toString(), 'code' => 'R10.9', 'description' => 'Unspecified abdominal pain', 'category' => 'Symptoms, signs and abnormal clinical and laboratory findings', 'is_active' => true, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['uuid' => service('uuid')->uuid4()->toString(), 'code' => 'R50.9', 'description' => 'Fever, unspecified', 'category' => 'Symptoms, signs and abnormal clinical and laboratory findings', 'is_active' => true, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['uuid' => service('uuid')->uuid4()->toString(), 'code' => 'R51.9', 'description' => 'Headache, unspecified', 'category' => 'Symptoms, signs and abnormal clinical and laboratory findings', 'is_active' => true, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['uuid' => service('uuid')->uuid4()->toString(), 'code' => 'S00.93XA', 'description' => 'Contusion of unspecified part of head, initial encounter', 'category' => 'Injury, poisoning and certain other consequences of external causes', 'is_active' => true, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['uuid' => service('uuid')->uuid4()->toString(), 'code' => 'S61.411A', 'description' => 'Laceration without foreign body of right hand, initial encounter', 'category' => 'Injury, poisoning and certain other consequences of external causes', 'is_active' => true, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['uuid' => service('uuid')->uuid4()->toString(), 'code' => 'S82.001A', 'description' => 'Fracture of unspecified part of right tibia, initial encounter', 'category' => 'Injury, poisoning and certain other consequences of external causes', 'is_active' => true, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['uuid' => service('uuid')->uuid4()->toString(), 'code' => 'S93.40XA', 'description' => 'Sprain of unspecified ligament of ankle, initial encounter', 'category' => 'Injury, poisoning and certain other consequences of external causes', 'is_active' => true, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['uuid' => service('uuid')->uuid4()->toString(), 'code' => 'T78.40XA', 'description' => 'Allergy, unspecified, initial encounter', 'category' => 'Injury, poisoning and certain other consequences of external causes', 'is_active' => true, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['uuid' => service('uuid')->uuid4()->toString(), 'code' => 'Z00.00', 'description' => 'Encounter for general adult medical examination without abnormal findings', 'category' => 'Factors influencing health status', 'is_active' => true, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['uuid' => service('uuid')->uuid4()->toString(), 'code' => 'Z23', 'description' => 'Encounter for immunization', 'category' => 'Factors influencing health status', 'is_active' => true, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['uuid' => service('uuid')->uuid4()->toString(), 'code' => 'Z96.1', 'description' => 'Presence of intraocular lens', 'category' => 'Factors influencing health status', 'is_active' => true, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['uuid' => service('uuid')->uuid4()->toString(), 'code' => 'M15.9', 'description' => 'Polyarthrosis, unspecified', 'category' => 'Diseases of the musculoskeletal system', 'is_active' => true, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['uuid' => service('uuid')->uuid4()->toString(), 'code' => 'J02.9', 'description' => 'Acute pharyngitis, unspecified', 'category' => 'Diseases of the respiratory system', 'is_active' => true, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
        ];

        $this->db->table('icd10_codes')->insertBatch($data);
    }
}
